# 配置服务端口号
server:
  port: 8080

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-user?characterEncoding=UTF8
    username: root
    password: 123456

# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.server.user.entity
  mapper-locations: classpath:/mapper/*.xml

knife4j:
  enable: true
  setting:
    language: zh_cn